name: Live Player Count

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks

    - name: Install LuaSocket
      run: luarocks install luasocket --local

    - name: Add LuaRocks local bin to PATH
      run: echo "LUAROCKS_BIN=$(luarocks path --lr-bin)" >> $GITHUB_ENV

    - name: Run live player count script
      env:
        PATH: ${{ env.LUAROCKS_BIN }}:$PATH
      run: lua live_player_count.lua
